export const BUILDING_BLUEPRINTS = [
  { id: 'workshop', name: '작업장', tier: 1, size: { width: 2, height: 2 }, inputs: { Wood: 10, Stone: 4 } },
  { id: 'kiln', name: '제재소', tier: 2, size: { width: 2, height: 2 }, inputs: { Wood: 8, Stone: 6 } },
  { id: 'quarry', name: '석재 가공소', tier: 2, size: { width: 2, height: 2 }, inputs: { Wood: 10, Stone: 10 } },
  { id: 'warehouse', name: '창고', tier: 2, size: { width: 2, height: 2 }, inputs: { Wood: 12, Stone: 10 }, storage: true },
  { id: 'forge', name: '제철소', tier: 3, size: { width: 2, height: 2 }, inputs: { Plank: 10, Brick: 8 } },
  { id: 'loom', name: '직물 공장', tier: 3, size: { width: 2, height: 2 }, inputs: { Plank: 8, Brick: 6 } },
  { id: 'farm', name: '농장', tier: 3, size: { width: 2, height: 2 }, inputs: { Plank: 10, Brick: 6 } },
  { id: 'water-tower', name: '정수장', tier: 3, size: { width: 2, height: 2 }, inputs: { Plank: 8, Brick: 8 } },
  { id: 'precision-shop', name: '유리 공장', tier: 3, size: { width: 2, height: 2 }, inputs: { Plank: 8, Brick: 10 } },
  { id: 'solar-array', name: '발전소', tier: 4, size: { width: 2, height: 2 }, inputs: { Steel: 8, Concrete: 12, Glass: 4 } },
  { id: 'habitat', name: '주거동', tier: 4, size: { width: 2, height: 2 }, inputs: { Plank: 15, Concrete: 15, Fabric: 8 } },
  { id: 'research-lab', name: '연구소', tier: 4, size: { width: 2, height: 2 }, inputs: { Steel: 12, Glass: 8, Fabric: 4 } },
  { id: 'machine-shop', name: '기계 공장', tier: 4, size: { width: 2, height: 2 }, inputs: { Steel: 15, Glass: 6, Brick: 8 } },
  { id: 'fuel-depot', name: '연료 공장', tier: 4, size: { width: 2, height: 2 }, inputs: { Steel: 12, Glass: 6, Brick: 8 } },
  { id: 'observatory', name: '소재 공장', tier: 4, size: { width: 2, height: 2 }, inputs: { Steel: 10, Glass: 10, Concrete: 10 } },
  { id: 'assembly-hall', name: '조립 공장', tier: 4, size: { width: 2, height: 2 }, inputs: { Steel: 20, Glass: 10, Fabric: 8 } },
  { id: 'spaceport', name: '발사대', tier: 5, size: { width: 3, height: 3 }, inputs: { Concrete: 30, Steel: 30, Glass: 20, Electronics: 12, MachineParts: 15 } },
  { id: 'rocket', name: '로켓', tier: 5, size: { width: 3, height: 2 }, inputs: { RocketFrame: 20, RocketEngine: 8, CircuitBoard: 12, Battery: 12 } },
]
