export const RESOURCE_CONFIG = {
  Food: { label: '식량', code: 'FO', kind: 'survival', gatherDuration: 2 },
  Water: { label: '물', code: 'WA', kind: 'survival', gatherDuration: 2 },
  Wood: { label: '나무', code: 'WD', kind: 'raw', gatherDuration: 2 },
  Stone: { label: '돌', code: 'ST', kind: 'raw', gatherDuration: 4 },
  Coal: { label: '석탄', code: 'CO', kind: 'raw', gatherDuration: 4 },
  IronOre: { label: '철광석', code: 'IR', kind: 'raw', gatherDuration: 4 },
  Fiber: { label: '섬유', code: 'FB', kind: 'raw', gatherDuration: 2 },
  Sand: { label: '모래', code: 'SA', kind: 'raw', gatherDuration: 2 },
  CopperOre: { label: '구리광석', code: 'CU', kind: 'raw', gatherDuration: 4 },
  CrudeOil: { label: '원유', code: 'OI', kind: 'raw', gatherDuration: 4 },
  Limestone: { label: '석회석', code: 'LS', kind: 'raw', gatherDuration: 4 },
  Bauxite: { label: '보크사이트', code: 'BX', kind: 'raw', gatherDuration: 4 },
  Quartz: { label: '석영', code: 'QZ', kind: 'raw', gatherDuration: 4 },
  Sulfur: { label: '유황', code: 'SU', kind: 'raw', gatherDuration: 4 },
  Plank: { label: '목재', code: 'PL', kind: 'processed' },
  Brick: { label: '벽돌', code: 'BR', kind: 'processed' },
  Steel: { label: '강철', code: 'SL', kind: 'processed' },
  Fabric: { label: '직물', code: 'FA', kind: 'processed' },
  Glass: { label: '유리', code: 'GL', kind: 'processed' },
  Copper: { label: '구리', code: 'CP', kind: 'processed' },
  Fuel: { label: '연료', code: 'FU', kind: 'processed' },
  Concrete: { label: '콘크리트', code: 'CN', kind: 'processed' },
  Aluminum: { label: '알루미늄', code: 'AL', kind: 'processed' },
  Silica: { label: '실리카', code: 'SI', kind: 'processed' },
  Electronics: { label: '전자부품', code: 'EL', kind: 'component' },
  MachineParts: { label: '기계부품', code: 'MP', kind: 'component' },
  CircuitBoard: { label: '회로기판', code: 'CB', kind: 'component' },
  Motor: { label: '모터', code: 'MO', kind: 'component' },
  Battery: { label: '배터리', code: 'BA', kind: 'component' },
  RocketFuel: { label: '로켓 연료', code: 'RF', kind: 'component' },
  RocketFrame: { label: '로켓 프레임', code: 'FR', kind: 'component' },
  RocketEngine: { label: '로켓 엔진', code: 'RE', kind: 'component' },
}

export const PROCESS_RECIPES = [
  { id: 'plank', name: '목재 가공', requires: 'kiln', inputs: { Wood: 2 }, output: { resource: 'Plank', amount: 1 } },
  { id: 'brick', name: '벽돌 생산', requires: 'quarry', inputs: { Stone: 2, Coal: 1 }, output: { resource: 'Brick', amount: 1 } },
  { id: 'steel', name: '강철 생산', requires: 'forge', inputs: { IronOre: 2, Coal: 1 }, output: { resource: 'Steel', amount: 1 } },
  { id: 'fabric', name: '직물 생산', requires: 'loom', inputs: { Fiber: 2 }, output: { resource: 'Fabric', amount: 1 } },
  { id: 'glass', name: '유리 생산', requires: 'precision-shop', inputs: { Sand: 2, Coal: 1 }, output: { resource: 'Glass', amount: 1 } },
  { id: 'concrete', name: '콘크리트 생산', requires: 'quarry', inputs: { Limestone: 2 }, output: { resource: 'Concrete', amount: 1 } },
  { id: 'silica', name: '실리카 생산', requires: 'precision-shop', inputs: { Quartz: 2 }, output: { resource: 'Silica', amount: 1 } },
  { id: 'copper', name: '구리 생산', requires: 'solar-array', inputs: { CopperOre: 2, Coal: 1 }, output: { resource: 'Copper', amount: 1 } },
  { id: 'fuel', name: '연료 생산', requires: 'fuel-depot', inputs: { CrudeOil: 2, Coal: 1 }, output: { resource: 'Fuel', amount: 1 } },
  { id: 'aluminum', name: '알루미늄 생산', requires: 'observatory', inputs: { Bauxite: 2, Coal: 1 }, output: { resource: 'Aluminum', amount: 1 } },
  { id: 'electronics', name: '전자부품 생산', requires: 'research-lab', inputs: { Copper: 2, Silica: 1 }, output: { resource: 'Electronics', amount: 1 } },
  { id: 'machine-parts', name: '기계부품 생산', requires: 'machine-shop', inputs: { Steel: 2, Copper: 1 }, output: { resource: 'MachineParts', amount: 1 } },
  { id: 'circuit-board', name: '회로기판 생산', requires: 'research-lab', inputs: { Copper: 2, Silica: 2 }, output: { resource: 'CircuitBoard', amount: 1 } },
  { id: 'motor', name: '모터 생산', requires: 'machine-shop', inputs: { Steel: 2, Electronics: 1 }, output: { resource: 'Motor', amount: 1 } },
  { id: 'battery', name: '배터리 생산', requires: 'observatory', inputs: { Aluminum: 2, Sulfur: 1 }, output: { resource: 'Battery', amount: 1 } },
  { id: 'rocket-fuel', name: '로켓 연료 생산', requires: 'fuel-depot', inputs: { Fuel: 2, Sulfur: 1 }, output: { resource: 'RocketFuel', amount: 1 } },
  { id: 'rocket-frame', name: '로켓 프레임 생산', requires: 'assembly-hall', inputs: { Aluminum: 3, Steel: 2 }, output: { resource: 'RocketFrame', amount: 1 } },
  { id: 'rocket-engine', name: '로켓 엔진 생산', requires: 'assembly-hall', inputs: { Motor: 2, MachineParts: 2 }, output: { resource: 'RocketEngine', amount: 1 } },
]

export const RESOURCE_NODE_TYPES = [
  { id: 'food', resource: 'Food' },
  { id: 'water', resource: 'Water' },
  { id: 'wood', resource: 'Wood' },
  { id: 'stone', resource: 'Stone' },
  { id: 'coal', resource: 'Coal' },
  { id: 'iron-ore', resource: 'IronOre' },
  { id: 'fiber', resource: 'Fiber' },
  { id: 'sand', resource: 'Sand' },
  { id: 'copper-ore', resource: 'CopperOre' },
  { id: 'crude-oil', resource: 'CrudeOil' },
  { id: 'limestone', resource: 'Limestone' },
  { id: 'bauxite', resource: 'Bauxite' },
  { id: 'quartz', resource: 'Quartz' },
  { id: 'sulfur', resource: 'Sulfur' },
]
